### ISSUE TITLE
test-map.cpp Change Request

### ISSUE THREAD

**Issue by carloa21** [kachmarma/cs4500-a1-p2#15]
Hello,
It seems like, in test-map.cpp, there is no cleaning procedure in the functions for objects allocated on the heap with "new". Per function, such as on line 8 and 9, the map and string allocated need to be deleted.
Thank you,
Carlo

**Comment by thomas-vaiarella** [comment]
Hi Carlo, my partner and I will be working today to delete the objects in our test file. I'll close this issue as soon as we push that!
