### ISSUE TITLE
String* or Object* const in cmp, concat, equals

### ISSUE THREAD

**Issue by 0816seung** [kachmarma/cs4500-a1-p2#18]
In String.h, cmp, concat, and equals all use const parameters such as `int cmp(String* const s);`.
This means that the passed in value must be a constant pointer to non-constant data.
This is not present in the Piazza post which simply uses no const values in these methods.
Could this be changed or explained?

**Comment by thomas-vaiarella** [comment]
We used the most recent API defined from the Piazza post here, which uses const: https://github.com/chasebish/cwc_object_string/blob/master/string.h
