### ISSUE TITLE
Remove to_string() from object.h

### ISSUE THREAD

**Issue by jaspersong** [kachmarma/cs4500-a1-p2#8]
Hello,

We are currently trying to reconcile the differences between object.h and string.h between the three teams. This spec's object.h is the only interface that differs from the others, because it includes a to_string() method. Please remove the function so it can be in-line with the other interface specs.

Thank you.

**Comment by TomPeng19971208** [comment]
hi, I suggest only add basic functionalities to object and string class
object:
1) virtual size_t hash()
2) virtual bool equals(Object* object)
String:
int compareTo()
String* concat(String* other)
